import type { FormDefinition, FormField } from "../form-engine/types";

const opt = (label: string) => ({ value: label, label });

const PADRAO_ACABAMENTO = [
  "Mínimo",
  "Baixo",
  "Normal / Baixo",
  "Normal",
  "Normal / Alto",
  "Alto",
  "Luxo",
].map(opt);

const ESTADO_CONSERVACAO = [
  "Bom",
  "Ruim (residual)",
  "Novo",
  "Reparos simples",
  "Reparos importantes",
].map(opt);

const counter = (
  id: string,
  label: string,
  extra?: Partial<FormField>
): FormField => ({ id, label, type: "counter", min: 0, ...extra });

export const apartmentForm: FormDefinition = {
  propertyType: "apartment",
  title: "Apartamento",
  subtitle: "Roteiro de análise - unidade prédio",
  sections: [
    {
      id: "identificacao",
      title: "Identificação",
      description: "Dados do imóvel. O número da OS vem da ordem de serviço.",
      order: 1,
      fields: [
        { id: "data", label: "Data", type: "date", required: true },
        { id: "cliente", label: "Cliente", type: "text", placeholder: "Nome do cliente" },
        { id: "edificio", label: "Edifício", type: "text", placeholder: "Nome do edifício" },
        { id: "apto", label: "Apto", type: "text", placeholder: "Ex.: 304 Bloco B", required: true },
      ],
    },
    {
      id: "regiao-infra",
      title: "Região - Infraestrutura",
      description: "Marque tudo que existe na região.",
      order: 2,
      fields: [
        {
          id: "infra",
          label: "Infra-estrutura urbana",
          type: "checkbox",
          options: [
            "Água",
            "Esgoto Pluvial",
            "Energia elétrica",
            "Esgoto ou Fossa",
            "Iluminação Pública",
            "Gás canalizado",
            "Telefone",
            "Pavimentação",
          ].map(opt),
        },
        {
          id: "evento",
          label: "Evento",
          type: "text",
          hint: "Campo do cabeçalho da ficha (preencha se houver).",
          placeholder: "Ex.: -",
        },
      ],
    },
    {
      id: "regiao-polos",
      title: "Região - Polos",
      description: "Valorizantes e desvalorizantes.",
      order: 3,
      fields: [
        {
          id: "polos_val",
          label: "Polos valorizantes",
          type: "checkbox",
          options: [
            "Sem influência",
            "Empreendimentos",
            "Shopping",
            "Indústria",
            "Parque",
            "Outros",
          ].map(opt),
        },
        {
          id: "polos_desval",
          label: "Polos desvalorizantes",
          type: "checkbox",
          options: [
            "Sem influência",
            "Empreendimentos",
            "Sub-Habitação",
            "Indústria",
            "Aterro Sanitário",
            "Estação de Tratamento",
            "Torres / Linhas de recepção e transmissão",
          ].map(opt),
        },
      ],
    },
    {
      id: "informante",
      title: "Informante",
      description: "Quem passou o valor de referência.",
      order: 4,
      fields: [
        { id: "valor", label: "Valor de Compra e Venda (R$)", type: "currency", placeholder: "R$ 0,00", required: true },
        { id: "nome_informante", label: "Nome do informante", type: "text", placeholder: "Nome" },
        {
          id: "contato",
          label: "Contato (Telefone ou e-mail)",
          type: "tel",
          placeholder: "(43) 99999-9999 ou e-mail",
        },
        {
          id: "classificacao",
          label: "Classificação",
          type: "checkbox",
          options: ["Comprador", "Vendedor", "Corretor", "Imobiliária", "Outros"].map(opt),
        },
      ],
    },
    {
      id: "bloco-dados",
      title: "Bloco / Prédio - Dados",
      description: "Números do prédio. Digite direto no campo.",
      order: 5,
      fields: [
        { id: "num_pavimentos", label: "Nº. de pavimentos", type: "number", placeholder: "Ex.: 12", min: 0 },
        { id: "aptos_por_pavimento", label: "Nº. de apto. por pavimento", type: "number", placeholder: "Ex.: 8", min: 0 },
        { id: "unidades_predio", label: "Nº. de unidades no prédio", type: "number", placeholder: "Ex.: 96", min: 0 },
        { id: "qtd_elevadores", label: "Quantidade de elevadores", type: "number", placeholder: "Ex.: 2", min: 0 },
        { id: "unidades_condominio", label: "Nº. de unidades no condomínio", type: "number", placeholder: "Ex.: 200", min: 0 },
        {
          id: "idade_estimada_predio",
          label: "Idade estimada",
          type: "text",
          placeholder: "Ex.: 12 anos",
        },
      ],
    },
    {
      id: "bloco-padrao",
      title: "Bloco / Prédio - Padrão",
      description: "Escolha uma opção em cada grupo.",
      order: 6,
      fields: [
        { id: "padrao_predio", label: "Padrão de acabamento", type: "radio", options: PADRAO_ACABAMENTO },
        { id: "conservacao_predio", label: "Estado de conservação", type: "radio", options: ESTADO_CONSERVACAO },
      ],
    },
    {
      id: "equip-condominio",
      title: "Equipamentos do condomínio",
      description: "Marque todos os existentes.",
      order: 7,
      fields: [
        {
          id: "equip_condominio",
          label: "Equipamentos do condomínio",
          type: "checkbox",
          options: [
            "Portaria e/ou guarita",
            "Equip. de segurança",
            "Salão de festas",
            "Play Groud",
            "Sauna / Ofurô",
            "Quadra poliesportiva",
            "Quadra de tênis",
            "Mini-quadra",
            "Piscina",
            "Espaço com Churrasqueira",
            "Aquecimento Solar",
            "Gerador",
            "Campo de futebol / Mini Golf",
            "Poço artesiano",
          ].map(opt),
        },
      ],
    },
    {
      id: "equip-bloco",
      title: "Equipamentos do bloco",
      description: "Marque todos os existentes.",
      order: 8,
      fields: [
        {
          id: "equip_bloco",
          label: "Equipamentos do bloco",
          type: "checkbox",
          options: ["Pilotis", "Rede interna de gás", "Central de aquecimento de água"].map(opt),
        },
      ],
    },
    {
      id: "unidade-divisao",
      title: "Unidade - Divisão interna",
      description: "Conte os cômodos com + / −.",
      order: 9,
      fields: [
        counter("q_quartos", "Quartos"),
        counter("q_cozinha", "Cozinha"),
        counter("q_banheiros_servico", "Banheiros de Serviço"),
        counter("q_circulacao", "Circulação"),
        counter("q_quarto_empregada", "Quarto de empregada"),
        counter("q_banheiros_sociais", "Banheiros Sociais"),
        counter("q_despensa", "Despensa"),
        counter("q_varanda", "Varanda/sacada"),
        counter("q_banheiros_privativos", "Banheiros Privativos"),
        counter("q_area_servico", "Área de serviço"),
        counter("q_armarios_completos", "Nº de armários completos"),
        counter("q_lavabos", "Lavabos"),
        { id: "sala", label: "Sala", type: "text", placeholder: "Ex.: 2 (estar + jantar)" },
        {
          id: "divisao_outros",
          label: "Outros",
          type: "textarea",
          rows: 3,
          placeholder: "Outros ambientes (um por linha)",
        },
      ],
    },
    {
      id: "unidade-equip-vista",
      title: "Unidade - Equipamentos e vista",
      order: 10,
      fields: [
        {
          id: "equip_unidade",
          label: "Equipamentos da unidade",
          type: "checkbox",
          options: ["Hidromassagem", "Ar condicionado", "Lareira", "Piscina", "Churrasqueira"].map(opt),
        },
        { id: "q_armarios_embutidos", label: "Quant. de armários embutidos", type: "counter" },
        {
          id: "vista",
          label: "Vista panorâmica",
          type: "radio",
          options: ["Favorável", "Desfavorável", "Sem Influência"].map(opt),
        },
        {
          id: "orientacao",
          label: "Orientação",
          type: "compass",
          hint: "Toque na direção predominante da unidade.",
          options: ["Norte", "Nordeste", "Leste", "Sudeste", "Sul", "Sudoeste", "Oeste", "Noroeste"].map(opt),
        },
      ],
    },
    {
      id: "unidade-padrao",
      title: "Unidade - Padrão",
      description: "Acabamento e conservação da unidade.",
      order: 11,
      fields: [
        { id: "padrao_unidade", label: "Padrão de acabamento", type: "radio", options: PADRAO_ACABAMENTO },
        { id: "conservacao_unidade", label: "Estado de conservação", type: "radio", options: ESTADO_CONSERVACAO },
        { id: "idade_estimada_unidade", label: "Idade estimada", type: "text", placeholder: "Ex.: 8 anos" },
      ],
    },
    {
      id: "garagem",
      title: "Vagas de garagem",
      order: 12,
      fields: [
        counter("vagas_cobertas", "Cobertas"),
        counter("vagas_descobertas", "Descobertas"),
        {
          id: "vagas_situacao",
          label: "Situação das vagas",
          type: "radio",
          options: [
            "Vagas rotativas",
            "Vagas de garagem informal",
            "Não existe vaga de garagem para todos apartamentos",
            "Nenhum apartamento possui vaga de garagem",
            "Todos apartamentos possuem vaga de garagem",
          ].map(opt),
        },
      ],
    },
    {
      id: "terreno-a",
      title: "Terreno - características",
      description: "Usos, serviços, cota e superfície.",
      order: 13,
      fields: [
        {
          id: "usos_predominantes",
          label: "Usos predominantes",
          type: "checkbox",
          options: [
            "Residencial Unifamiliar",
            "Residencial Multifamiliar",
            "Comercial",
            "Institucional",
            "Industrial",
          ].map(opt),
        },
        {
          id: "servicos",
          label: "Serviços públicos e comunitários",
          type: "checkbox",
          options: [
            "Coleta de lixo",
            "Comércio",
            "Transporte coletivo",
            "Rede bancária",
            "Escola",
            "Saúde",
            "Lazer",
            "Segurança",
          ].map(opt),
        },
        {
          id: "cota",
          label: "Cota / Greide",
          type: "radio",
          options: ["Mesmo nível", "Acima", "Abaixo"].map(opt),
        },
        {
          id: "inclinacao",
          label: "Inclinação",
          type: "radio",
          options: ["Plano", "Aclive p/ o fundo", "Declive p/ o fundo"].map(opt),
        },
        {
          id: "situacao",
          label: "Situação",
          type: "radio",
          options: ["Meio de quadra", "Esquina", "Quadra inteira", "Outros"].map(opt),
          allowOtherDetail: true,
          otherDetailId: "situacao_outros",
          otherDetailLabel: "Qual?",
        },
        {
          id: "superficie",
          label: "Superfície",
          type: "radio",
          options: ["Seco", "Brejoso", "Alagável", "Outros"].map(opt),
          allowOtherDetail: true,
          otherDetailId: "superficie_outros",
          otherDetailLabel: "Qual?",
        },
      ],
    },
    {
      id: "terreno-b",
      title: "Terreno - edificação",
      description: "Categoria, posição e uso do prédio.",
      order: 14,
      fields: [
        {
          id: "categoria",
          label: "Categoria",
          type: "radio",
          options: [
            "Apartamento",
            "Flat",
            "Kitnet",
            "Sala comum",
            "Loft",
            "Pavimento corrido",
          ].map(opt),
        },
        {
          id: "uso_unidade",
          label: "Uso da unidade",
          type: "radio",
          options: ["Residencial", "Comercial", "Industrial", "Misto"].map(opt),
        },
        {
          id: "tetos",
          label: "Tetos",
          type: "checkbox",
          options: ["Forro", "Laje", "Telhado aparente", "Outros"].map(opt),
        },
        {
          id: "fechamento_paredes",
          label: "Fechamento das paredes",
          type: "checkbox",
          options: ["Alvenaria", "Madeira", "Gesso", "Outros"].map(opt),
        },
        {
          id: "ident_pavimentos",
          label: "Identificação dos pavimentos",
          type: "text",
          placeholder: "Ex.: térreo + 8 pavimentos",
        },
        {
          id: "posicao_edificacao",
          label: "Posição da edificação no terreno",
          type: "radio",
          options: ["Isolada / Frente do Terreno", "Isolada / Centro do Terreno", "Outros"].map(opt),
          allowOtherDetail: true,
          otherDetailId: "posicao_edificacao_outros",
          otherDetailLabel: "Qual?",
        },
        {
          id: "posicao_unidade",
          label: "Posição da unidade no prédio / bloco",
          type: "checkbox",
          options: [
            "Frente / Canto",
            "Fundos / Canto",
            "Frente / Meio",
            "Fundos / Meio",
            "Lateral",
            "Outros",
          ].map(opt),
        },
        {
          id: "uso_predio",
          label: "Uso do prédio",
          type: "radio",
          options: ["Residencial", "Comercial", "Industrial", "Misto"].map(opt),
        },
        {
          id: "area_nao_averbada",
          label: "Há área não averbada?",
          type: "yesno",
          hint: "Se sim, descreva abaixo.",
          otherDetailId: "area_nao_averbada_det",
          otherDetailLabel: "Descreva a área não averbada",
        },
      ],
    },
    {
      id: "checklist",
      title: "Checklist final",
      description: "Condições do imóvel. Detalhe quando necessário.",
      order: 15,
      fields: [
        {
          id: "estabilidade",
          label: "O imóvel apresenta condições de estabilidade e solidez?",
          type: "yesno",
        },
        { id: "estabilidade_det", label: "Detalhe (estabilidade)", type: "text", placeholder: "Opcional" },
        {
          id: "habitabilidade",
          label: "O imóvel apresenta condições de habitabilidade?",
          type: "yesno",
        },
        { id: "habitabilidade_det", label: "Detalhe (habitabilidade)", type: "text", placeholder: "Opcional" },
        {
          id: "vicios",
          label: "Vícios de construção aparente",
          type: "checkbox",
          options: ["Não", "Fissuras", "Manchas de umidade", "Outro"].map(opt),
        },
        {
          id: "vicios_det",
          label: "Detalhe dos vícios",
          type: "textarea",
          rows: 2,
          placeholder: "Descreva fissuras, manchas, outro...",
        },
        {
          id: "observacoes",
          label: "Observações / croqui",
          type: "textarea",
          rows: 3,
          placeholder: "Anotações livres da vistoria",
        },
      ],
    },
  ],
};
