import type { FormDefinition, FormField } from "../form-engine/types";

const opt = (label: string) => ({ value: label, label });

const PADRAO_ACABAMENTO = [
  "Mínimo",
  "Baixo",
  "Normal / Baixo",
  "Normal",
  "Normal / Alto",
  "Alto",
  "Luxo",
].map(opt);

const counter = (
  id: string,
  label: string,
  extra?: Partial<FormField>
): FormField => ({ id, label, type: "counter", min: 0, ...extra });

export const houseForm: FormDefinition = {
  propertyType: "house",
  title: "Casa",
  subtitle: "Roteiro de análise — unidade isolada",
  sections: [
    {
      id: "identificacao",
      title: "Identificação",
      description: "Dados do imóvel. O número da OS vem da ordem de serviço.",
      order: 1,
      fields: [
        { id: "data", label: "Data", type: "date", required: true },
        { id: "cliente", label: "Nome do cliente", type: "text", placeholder: "Nome do cliente" },
        { id: "endereco_rua", label: "Endereço vistoriado — rua", type: "text", placeholder: "Ex.: Rua das Flores" },
        {
          id: "numeracao_predial",
          label: "Há numeração predial?",
          type: "yesno",
          otherDetailId: "numeracao_predial_num",
          otherDetailLabel: "Número",
        },
      ],
    },
    {
      id: "regiao-infra",
      title: "Região — Infraestrutura",
      description: "Marque tudo que existe na região.",
      order: 2,
      fields: [
        {
          id: "infra",
          label: "Infra-estrutura urbana",
          type: "checkbox",
          options: [
            "Água",
            "Esgoto pluvial",
            "Energia elétrica",
            "Esgoto ou fossa",
            "Iluminação Pública",
            "Gás canalizado",
            "Telefone",
            "Pavimentação",
          ].map(opt),
        },
      ],
    },
    {
      id: "regiao-polos",
      title: "Região — Polos",
      description: "Valorizantes e desvalorizantes.",
      order: 3,
      fields: [
        {
          id: "polos_val",
          label: "Polos valorizantes",
          type: "checkbox",
          options: [
            "Sem influência",
            "Parques",
            "Empreendimentos",
            "Shoping Center",
            "Indústria",
            "Outros",
          ].map(opt),
        },
        {
          id: "polos_desval",
          label: "Polos desvalorizantes",
          type: "checkbox",
          options: [
            "Sem influência",
            "Aterro Sanitário",
            "Torres / Linhas de recepção e transmissão",
            "Empreendimentos",
            "Sub-Habitação",
            "Indústria",
            "Estação de Tratamento",
          ].map(opt),
        },
      ],
    },
    {
      id: "informante",
      title: "Informante",
      description: "Quem passou o valor de referência.",
      order: 4,
      fields: [
        { id: "valor", label: "Valor Pretendido (R$)", type: "currency", placeholder: "R$ 0,00", required: true },
        { id: "nome_informante", label: "Nome do informante", type: "text", placeholder: "Nome" },
        {
          id: "contato",
          label: "Contato (Telefone ou e-mail)",
          type: "tel",
          placeholder: "(43) 99999-9999 ou e-mail",
        },
        {
          id: "classificacao",
          label: "Classificação",
          type: "checkbox",
          options: ["Comprador", "Corretor", "Outros", "Vendedor", "Imobiliária"].map(opt),
        },
      ],
    },
    {
      id: "unidade-divisao",
      title: "Unidade — Divisão interna",
      description: "Conte os cômodos com + / −.",
      order: 5,
      fields: [
        counter("q_quartos", "Quartos"),
        counter("q_cozinha", "Cozinha"),
        counter("q_banheiros_servico", "Banheiros de Serviço"),
        counter("q_circulacao", "Circulação"),
        counter("q_quarto_empregada", "Quarto de empregada"),
        counter("q_banheiros_sociais", "Banheiros Sociais"),
        counter("q_despensa", "Despensa"),
        counter("q_varanda", "Varanda/sacada"),
        counter("q_banheiros_privativos", "Banheiros Privativos"),
        counter("q_area_servico", "Área de serviço"),
        counter("q_armarios_completos", "Nº de armários completos"),
        counter("q_lavabos", "Lavabos"),
        { id: "sala", label: "Sala", type: "text", placeholder: "Ex.: 2 (estar + jantar)" },
        {
          id: "divisao_outros",
          label: "Outros",
          type: "textarea",
          rows: 3,
          placeholder: "Outros ambientes (um por linha)",
        },
      ],
    },
    {
      id: "garagem-idade",
      title: "Garagem e idade",
      description: "Vagas e idade aparente do imóvel.",
      order: 6,
      fields: [
        counter("vagas_cobertas", "Cobertas"),
        counter("vagas_descobertas", "Descobertas"),
        {
          id: "idade_aparente_novo",
          label: "Idade aparente",
          type: "checkbox",
          options: ["Novo"].map(opt),
        },
        { id: "idade_anos", label: "Anos", type: "number", placeholder: "Ex.: 10", min: 0 },
      ],
    },
    {
      id: "unidade-posicao",
      title: "Unidade — Posição e lote",
      description: "Escolha uma opção em cada grupo.",
      order: 7,
      fields: [
        {
          id: "posicao",
          label: "Posição",
          type: "radio",
          options: [
            "Isolada",
            "Geminada nas laterais",
            "Junto às laterais",
            "Ocupa todo o terreno",
            "Junto a uma das laterais",
          ].map(opt),
        },
        {
          id: "implantacao",
          label: "Implantação",
          type: "radio",
          options: ["Isolada", "Geminada", "Justaposta"].map(opt),
        },
        {
          id: "fechamento_lote",
          label: "Fechamento do lote",
          type: "radio",
          options: ["Inexistente", "Parcial", "Total"].map(opt),
        },
        {
          id: "piso",
          label: "Piso",
          type: "radio",
          options: ["Com Revestimento", "Sem revestimento"].map(opt),
        },
      ],
    },
    {
      id: "unidade-cobertura-equip",
      title: "Unidade — Cobertura e equipamentos",
      description: "Marque todos os existentes.",
      order: 8,
      fields: [
        {
          id: "cobertura",
          label: "Cobertura",
          type: "checkbox",
          options: [
            "Fibrocimento",
            "Telha Metálica",
            "Telha de Barro",
            "Madeira",
            "Telha de Concreto",
            "Outros",
          ].map(opt),
        },
        {
          id: "equip_unidade",
          label: "Equipamentos da unidade",
          type: "checkbox",
          options: [
            "Churrasqueira",
            "Hidromassagem",
            "Aquecimento Solar",
            "Lareira",
            "Quadra",
            "Ar-Condicionado",
            "Piscina",
            "Sauna",
          ].map(opt),
        },
      ],
    },
    {
      id: "esquadrias",
      title: "Esquadrias",
      description: "Material predominante em cada grupo.",
      order: 9,
      fields: [
        {
          id: "esquadrias_fachada",
          label: "Fachada principal",
          type: "radio",
          options: ["Alumínio", "Vidro Temperado", "Aço", "Madeira", "PVC"].map(opt),
        },
        {
          id: "esquadrias_demais",
          label: "Demais",
          type: "radio",
          options: ["Alumínio", "Vidro Temperado", "Aço", "Madeira", "PVC"].map(opt),
        },
      ],
    },
    {
      id: "unidade-padrao",
      title: "Unidade — Padrão",
      description: "Acabamento e conservação da unidade.",
      order: 10,
      fields: [
        { id: "padrao_unidade", label: "Padrão de acabamento", type: "radio", options: PADRAO_ACABAMENTO },
        {
          id: "conservacao_unidade",
          label: "Estado de conservação",
          type: "radio",
          options: [
            "Ruim (residual)",
            "Regular",
            "Reparos importantes",
            "Bom",
            "Reparos simples",
            "Novo",
          ].map(opt),
        },
      ],
    },
    {
      id: "terreno",
      title: "Terreno",
      description: "Usos, serviços e características do lote.",
      order: 11,
      fields: [
        {
          id: "usos_predominantes",
          label: "Usos predominantes",
          type: "checkbox",
          options: [
            "Residencial Unifamiliar",
            "Residencial Multifamiliar",
            "Comercial",
            "Industrial",
            "Institucional",
          ].map(opt),
        },
        {
          id: "servicos",
          label: "Serviços disponíveis no bairro",
          type: "checkbox",
          options: [
            "Coleta de lixo",
            "Transporte coletivo",
            "Comércio",
            "Rede bancária",
            "Escola",
            "Saúde",
            "Segurança",
            "Lazer",
          ].map(opt),
        },
        {
          id: "cota",
          label: "Cota / Greide",
          type: "radio",
          options: ["Mesmo nível", "Abaixo", "Acima"].map(opt),
        },
        {
          id: "inclinacao",
          label: "Inclinação",
          type: "radio",
          options: ["Plano", "Declive", "Aclive"].map(opt),
        },
        {
          id: "situacao",
          label: "Situação",
          type: "radio",
          options: ["Meio de quadra", "Esquina", "Quadra inteira", "Outros"].map(opt),
          allowOtherDetail: true,
          otherDetailId: "situacao_outros",
          otherDetailLabel: "Qual?",
        },
        {
          id: "superficie",
          label: "Superfície",
          type: "radio",
          options: ["Seco", "Brejoso", "Alagável", "Outros"].map(opt),
          allowOtherDetail: true,
          otherDetailId: "superficie_outros",
          otherDetailLabel: "Qual?",
        },
        {
          id: "uso_unidade",
          label: "Uso da unidade",
          type: "radio",
          options: ["Residencial", "Comercial", "Industrial", "Misto"].map(opt),
        },
        {
          id: "teto",
          label: "Teto",
          type: "checkbox",
          options: ["Forro", "Laje", "Telhado Aparente", "Outros"].map(opt),
        },
        {
          id: "fechamento_paredes",
          label: "Fechamento das paredes",
          type: "checkbox",
          options: ["Alvenaria", "Madeira", "Outros", "Gesso", "Madeira/Alvenaria"].map(opt),
        },
      ],
    },
    {
      id: "checklist",
      title: "Checklist final",
      description: "Condições do imóvel. Detalhe quando necessário.",
      order: 12,
      fields: [
        {
          id: "estabilidade",
          label: "O imóvel apresenta condições de estabilidade e solidez?",
          type: "yesno",
        },
        { id: "estabilidade_det", label: "Detalhe (estabilidade)", type: "text", placeholder: "Opcional" },
        {
          id: "habitabilidade",
          label: "O imóvel apresenta condições de habitabilidade?",
          type: "yesno",
        },
        { id: "habitabilidade_det", label: "Detalhe (habitabilidade)", type: "text", placeholder: "Opcional" },
        {
          id: "vicios",
          label: "O imóvel apresenta vícios de construção aparente?",
          type: "checkbox",
          options: ["Não", "Fissuras", "Manchas de umidade", "Outro"].map(opt),
        },
        {
          id: "vicios_det",
          label: "Detalhe dos vícios",
          type: "textarea",
          rows: 2,
          placeholder: "Descreva fissuras, manchas, outro...",
        },
        {
          id: "croqui",
          label: "Croqui",
          type: "textarea",
          rows: 3,
          placeholder: "Descreva o croqui ou pontos de referência",
        },
        {
          id: "janelas_perp",
          label: "Há janelas perpendiculares à divisa?",
          type: "yesno",
          otherDetailId: "janelas_perp_det",
          otherDetailLabel: "Quais?",
        },
        {
          id: "aberturas_irreg",
          label: "Há aberturas irregulares (paralelas à divisa, voltadas para ambiente)?",
          type: "yesno",
          otherDetailId: "aberturas_irreg_det",
          otherDetailLabel: "Quais?",
        },
        {
          id: "pintura_divisas",
          label: "Há pintura externa nas divisas?",
          type: "yesno",
        },
        {
          id: "pintura",
          label: "Pintura",
          type: "checkbox",
          options: ["Externa", "Interna"].map(opt),
        },
        {
          id: "area_nao_averbada",
          label: "Há áreas aparentemente não averbadas?",
          type: "yesno",
          otherDetailId: "area_nao_averbada_det",
          otherDetailLabel: "Descreva as áreas",
        },
        {
          id: "esgoto",
          label: "Solução de esgoto sanitário",
          type: "radio",
          options: ["Fossa séptica", "Esgoto"].map(opt),
        },
      ],
    },
    {
      id: "condominio",
      title: "Condomínio (complemento)",
      description: "Preencha se a casa for em condomínio. Caso contrário, deixe em branco.",
      order: 13,
      fields: [
        {
          id: "cond_equip",
          label: "Equipamentos",
          type: "checkbox",
          options: [
            "Portaria ou Guarita",
            "Equipamento de Segurança",
            "Salão de Festas",
            "Play Ground",
            "Sauna / ou Ofurô",
            "Quadra Poliesportiva",
            "Quadra de Tênis",
            "Mini Quadra",
            "Piscina",
            "Espaço com Churrasqueira",
            "Aquecimento Solar",
            "Gerador",
            "Campo de futebol / Mini Golfe",
            "Poço Artesiano",
          ].map(opt),
        },
        {
          id: "cond_fechamento_contorno",
          label: "Fechamento de Contorno do Condomínio",
          type: "checkbox",
          options: ["Alvenaria", "Alambrado", "Cerca Viva", "Grade Metálica"].map(opt),
        },
        {
          id: "cond_fechamento_grau",
          label: "Fechamento do contorno — grau",
          type: "radio",
          options: ["Total", "Parcial", "Inexistente"].map(opt),
        },
        {
          id: "cond_insercao",
          label: "Inserção do Condomínio",
          type: "radio",
          options: ["Isolado", "Inserido em Conjunto Habitacional", "Inserido em outro Condomínio"].map(opt),
        },
      ],
    },
  ],
};
